baseURL = 'https://whatmakeart.com/experiments-in-electronic-arts/'
languageCode = 'en-us'
title = 'Experiments in Electronic Arts'
theme = 'basicTheme'

SectionPagesMenu = "main"
Paginate = 18 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-S4CF1KSMYD"
enableRobotsTXT = true
custom_css = "css/styles.css"

pygmentsCodefences = true
pygmentsStyle = "pygments"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  
  authorName = "Jimmy Kuehnle"
  favicon = "/favicon/favicon.ico"
  site_logo = "/img/whatmakeart-logo.png"
  description = "Experiments in Electronic Arts"
  facebook = ""
  twitter = "https://twitter.com/whatmakeart"
  instagram = "https://www.instagram.com/whatmakeart/"
  youtube = "https://www.youtube.com/channel/UCmGXH-jy0o2CuhqtpxbaQgA"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
    unsafe= true # needed to have html parsed in markdown files

[markup.highlight]
  anchorLineNos = false
  codeFences = true
   guessSyntax = false
   hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'arduino'
    tabWidth = 4


    


